apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: videoplayer  
  name: videoplayerdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: videoplayer
  template:
    metadata:
      labels:
        name: videoplayer
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        command: ["mongod"]
      - name: videoplayercontainer
        image: alfredxgxg123/videoplayer:latest
        ports:
        - containerPort: 8080
        command: ["sh", "-c", "npm run startdev"]






