version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: videoplayer
    build: .
    command: bash -c  "
      npm run build
      && npm run seed
      && npm start"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
