apiVersion: v1
kind: Service
metadata:
  name: videoplayerservice
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
      name: videoplayer
  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo