apiVersion: v1
kind: Service
metadata:
  name: videoplayerservice
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30001
  selector:
    name: videoplayer

# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   labels:
#     name: mongo
# spec:
#   ports:
#   - port: 27017
#     targetPort: 30001
#   selector:
#     name: mongo

